#!/usr/bin/env bash
set -e 
../emboss/embossc packets.emb
cp ../emboss/runtime/cpp/*.h emboss/

find . -name "*.h" -exec sed -i -e 's:runtime/cpp/::' '{}' \;

for subdir in controller remote; do
  cp packets.emb.h "${subdir}"/packets.emb.h
  cp emboss/* "${subdir}"/
done
